CREATE DATABASE IF NOT EXISTS mydatabase;
USE mydatabase;

CREATE TABLE IF NOT EXISTS links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    shortLink VARCHAR(10) NOT NULL,
    longLink VARCHAR(2083) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
